<?php
$title = $this->translate('Apagar Serviço');
$this->headTitle($title);
$url = $this->url('dtl-admin/dtl-occupation/delete', array('id' => $this->occupation->getId()));
?>
<div class="modal-header">
    <h3 class="modal-title txt-color-teal"><i class='fas fa-trash'></i>&nbsp;<?php echo $this->escapeHtml($title); ?></h3>
</div>
<div class="modal-body">
    <blockquote>
        <?php echo $this->translate('Deseja excluir ') ?>
        '<?php echo $this->escapeHtml($this->occupation->getName()); ?>'?
    </blockquote>
</div>
<div class="modal-footer">
    <form action="<?php echo $url; ?>" method="post">
        <input type="hidden" name="id" value="<?php echo $this->occupation->getId(); ?>" />
        <button type="submit" name="del" value="Sim" class="btn btn-danger"><i class="fa fa-eraser"></i>&nbsp;<?php echo $this->translate('Sim'); ?></button>
        <button class="btn btn-secondary" type="button" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;<?php echo $this->translate('Não'); ?></button>
    </form>
</div>